stream-cursor/cursor-publishers/src/main/java/com/backbase/stream/cursor/events/AuditLoginEventListener.java
stream-cursor/cursor-publishers/src/main/java/com/backbase/stream/cursor/events/PaymentListener.java

https://community.backbase.com/documentation/DBS/2-19-1/audit_reference#audit_2_19_0_upgrade_lean_events
> The Audit event classes are now as follows:
> com.backbase.audit.persistence.event.spec.v1.AuditClientCreateMessagesEvent
> 
> **com.backbase.audit.persistence.event.spec.v1.AuditMessagesCreatedEvent**
> 
> com.backbase.audit.persistence.event.spec.v1.AuditMessagesRetrievedEvent
> 
> com.backbase.audit.persistence.event.spec.v1.CreateAuditMessagesFailedEvent
> 
> com.backbase.audit.persistence.event.spec.v1.EventCategoriesRetrievedEvent
> 
> com.backbase.audit.persistence.event.spec.v1.RetrieveAuditMessagesFailedEvent
> 
> com.backbase.audit.persistence.event.spec.v1.RetrieveEventCategoriesFailedEvent
> 
>

Fix topic for audit login event

---

api/stream-legal-entity/openapi.yaml
stream-access-control/access-control-core/src/main/java/com/backbase/stream/mapper/AccessGroupMapper.java
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java
stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java

We keep it backwards compatible with reference job roles creation and also include the possibility of creating custom job roles (not reference) in the service agreement level, that can be assigned to any users created by other means (employee app, for example). Useful for legal entity bootstrapping.

Including job roles creation detached from users or products creation.

---

CHANGELOG.md
stream-product/product-core/src/main/java/com/backbase/stream/product/utils/StreamUtils.java

This fix is to avoid NullPointerException when creating data group of type products i.e. without custom data group id.

Fixing NullPointerException for Data group creation

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java

This fix deletes the function groups only if it is not of Template Type. @uesleilima

Fixing the delete issue when using reference job roles. 

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java
stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/AccessGroupServiceTest.java

In general filtering logic was moved slightly upper in order to preserve original code that would assign given permissions in request when none returned from API

Fix for previous fix regarding SFG appearing in get permissions response

---

stream-compositions/api/service-api/legal-entity-composition-api/src/main/resources/service-api-v2.yaml
stream-compositions/api/service-api/product-catalog-composition-api/src/main/resources/service-api-v2.yaml
stream-compositions/api/service-api/product-composition-api/src/main/resources/service-api-v2.yaml
stream-compositions/services/legal-entity-composition-service/src/main/java/com/backbase/stream/compositions/legalentity/http/LegalEntityController.java
stream-compositions/services/legal-entity-composition-service/src/test/java/com/backbase/stream/compositions/legalentity/http/LegalEntityControllerIT.java
stream-compositions/services/legal-entity-composition-service/src/test/java/com/backbase/stream/compositions/legalentity/http/LegalEntityControllerTest.java
stream-compositions/services/product-catalog-composition-service/src/main/java/com/backbase/stream/compositions/productcatalog/http/ProductCatalogController.java
stream-compositions/services/product-catalog-composition-service/src/test/java/com/nackbase/stream/compositions/productcatalog/http/ProductCatalogControllerIT.java
stream-compositions/services/product-catalog-composition-service/src/test/java/com/nackbase/stream/compositions/productcatalog/http/ProductCatalogControllerTest.java
stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/http/ProductController.java
stream-compositions/services/product-composition-service/src/test/java/com/backbase/stream/compositions/product/http/ProductControllerIT.java
stream-compositions/services/product-composition-service/src/test/java/com/backbase/stream/compositions/product/http/ProductControllerTest.java

Updated compositions api naming.

Updated compositions api naming.

---

CHANGELOG.md
stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/BatchProductIngestionSaga.java

Fixes #138 
Solved by adding a null check before checking for an empty list.
https://github.com/Backbase/stream-services/blob/2c5e54e58badadfe1f7cadb3b8dfcdd27c21dbb6/stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/BatchProductIngestionSaga.java#L118

BugFix #138 - Fixes NPE when there are no products.

---

CHANGELOG.md
stream-legal-entity/legal-entity-http/src/test/java/com/backbase/stream/it/LegalEntitySagaIT.java
stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/BatchProductIngestionSaga.java

Using the UI, it is possible to create an account group with no accounts, i.e., it is possible to create a product-group with no data-items.
There is a valid use-case for it: In NBC, we wish to create an "All-Accounts" group which is empty and assign permissions to users on this account group. Then we can add arrangements to the account-group.

Allow empty product groups to be created

---

CHANGELOG.md
stream-product/product-ingestion-saga/pom.xml
stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/BusinessFunctionGroupMapper.java
stream-product/product-ingestion-saga/src/test/java/com/backbase/stream/product/BusinessFunctionGroupMapperTest.java

Fix for [MS-495 & MS-171](https://backbase.atlassian.net/browse/MS-495?atlOrigin=eyJpIjoiMWIzYzY3YmRjOTE1NDFjOWI0OGU2N2JlYWMxNGU2ZDQiLCJwIjoiaiJ9)
With Current Stream Implementation, Able to Create custom job role in a Service agreement but when a user is assigned this role, all the permission from job role table disappears, this fix will map privileges during the mapping from FunctionGroupItem (Access Control) to BusinessFunction (Streams) objects
Fix for Issue: https://github.com/Backbase/stream-services/issues/166

Fix for Custom Job Role Privileges missing when assigned to a user

---

CHANGELOG.md
stream-contacts/contacts-core/src/main/java/com/backbase/stream/configuration/ContactsServiceConfiguration.java

While just using `LegalEntitySagaConfiguration` we are unable to start the application as there is a bean conflict.
``` log
+[ Description:
+[ 
+[ Parameter 0 of method contactsApi in com.backbase.stream.configuration.ContactsServiceConfiguration required a single bean, but 2 were found:
+[ 	- accessProviderWebClient: defined by method 'accessProviderWebClient' in class path resource [com/backbase/buildingblocks/webclient/InterServiceWebClientConfiguration$Oauth2ClientConfiguration.class]
+[ 	- interServiceWebClient: defined by method 'interServiceWebClient' in class path resource [com/backbase/buildingblocks/webclient/InterServiceWebClientConfiguration.class]
```
To resolve this added a qualifier for `WebClient`.

Added qualifier for WebClient in ContactsServiceConfiguration.

---

api/stream-legal-entity/openapi.yaml

- Added missing attribute "OverdueSince"
- Moved "DebitCardItems" array to BaseProduct since DebitCards is part of https://developer.backbase.com/api/specs/arrangement-manager/arrangement-service-api/2.7.3/models/AccountArrangementItemBase
- Moved "AmountInArrear" to BaseProduct since AmountInArrear is part of https://developer.backbase.com/api/specs/arrangement-manager/arrangement-service-api/2.7.3/models/AbstractArrangementItemBase

Added support for AccountServicing/E-Collections

---

CHANGELOG.md
stream-compositions/pom.xml

Added zip layout to composition services. This allows the addition of external jars to the classpath using `loader.path` property.

Zip layout for composition services

---

.gitignore
CHANGELOG.md
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/mapper/PaymentOrderMapper.java
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/model/PaymentOrderIngestResponse.java
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/service/PaymentOrderPostIngestionService.java
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/service/impl/PaymentOrderIngestionServiceImpl.java
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/service/impl/PaymentOrderPostIngestionServiceImpl.java
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/http/PaymentOrderController.java
stream-compositions/services/payment-order-composition-service/src/test/java/com/backbase/stream/compositions/paymentorders/core/service/impl/PaymentOrderIngestionServiceImplTest.java
stream-compositions/services/payment-order-composition-service/src/test/java/com/backbase/stream/compositions/paymentorders/http/PaymentOrderControllerIT.java
stream-compositions/services/payment-order-composition-service/src/test/java/com/backbase/stream/compositions/paymentorders/http/PaymentOrderControllerTest.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/config/PaymentOrderServiceConfiguration.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/config/PaymentOrderWorkerConfigurationProperties.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/PaymentOrderIngestContext.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/request/DeletePaymentOrderIngestRequest.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/request/NewPaymentOrderIngestRequest.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/request/PaymentOrderIngestRequest.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/request/UpdatePaymentOrderIngestRequest.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/response/DeletePaymentOrderIngestDbsResponse.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/response/NewPaymentOrderIngestDbsResponse.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/response/PaymentOrderIngestDbsResponse.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/response/UpdatePaymentOrderIngestDbsResponse.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderTask.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderTaskExecutor.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderUnitOfWorkExecutor.java

problems in the stream-services internal code:
=> the delete payments step is not working because the reactor event flow is not connected correctly.
possible solution in the PaymentOrderTaskExecutor class:
```
private Mono<String> deletePaymentOrder(String internalPaymentOrderId) {
return paymentOrdersApi.deletePaymentOrder(internalPaymentOrderId)
.thenReturn(internalPaymentOrderId);
}
```
=> the newPaymentOrder, updatePaymentOrder and deletePaymentOrder list calculation logic is not working properly because the method that processes it uses only a partial list of 10 PaymentOrderPostRequest at a time, sometimes causing inconsistency in checking whether a payment order should be updated or not, for example. This happens because the PaymentOrderTask execution is configured to be emitted …

reorganization of payment ingestion logic

---

.gitignore
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/mapper/PaymentOrderMapper.java
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/model/PaymentOrderIngestResponse.java
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/service/PaymentOrderPostIngestionService.java
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/service/impl/PaymentOrderIngestionServiceImpl.java
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/service/impl/PaymentOrderPostIngestionServiceImpl.java
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/http/PaymentOrderController.java
stream-compositions/services/payment-order-composition-service/src/test/java/com/backbase/stream/compositions/paymentorders/core/service/impl/PaymentOrderIngestionServiceImplTest.java
stream-compositions/services/payment-order-composition-service/src/test/java/com/backbase/stream/compositions/paymentorders/http/PaymentOrderControllerIT.java
stream-compositions/services/payment-order-composition-service/src/test/java/com/backbase/stream/compositions/paymentorders/http/PaymentOrderControllerTest.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/config/PaymentOrderServiceConfiguration.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/config/PaymentOrderWorkerConfigurationProperties.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/PaymentOrderIngestContext.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/request/DeletePaymentOrderIngestRequest.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/request/NewPaymentOrderIngestRequest.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/request/PaymentOrderIngestRequest.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/request/UpdatePaymentOrderIngestRequest.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/response/DeletePaymentOrderIngestDbsResponse.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/response/NewPaymentOrderIngestDbsResponse.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/response/PaymentOrderIngestDbsResponse.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/response/UpdatePaymentOrderIngestDbsResponse.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderTask.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderTaskExecutor.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderUnitOfWorkExecutor.java

problems in the stream-services internal code:
=> the delete payments step is not working because the reactor event flow is not connected correctly.
possible solution in the PaymentOrderTaskExecutor class:
```
private Mono<String> deletePaymentOrder(String internalPaymentOrderId) {
return paymentOrdersApi.deletePaymentOrder(internalPaymentOrderId)
.thenReturn(internalPaymentOrderId);
}
```
=> the newPaymentOrder, updatePaymentOrder and deletePaymentOrder list calculation logic is not working properly because the method that processes it uses only a partial list of 10 PaymentOrderPostRequest at a time, sometimes causing inconsistency in checking whether a payment order should be updated or not, for example. This happens because the PaymentOrderTask execution is configured to be emitted …

reorganization of payment ingestion logic master

---

stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/mapper/PaymentOrderMapper.java
stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/service/impl/PaymentOrderIntegrationServiceImpl.java
stream-compositions/services/payment-order-composition-service/src/test/java/com/backbase/stream/compositions/paymentorders/http/PaymentOrderControllerTest.java
stream-configuration/src/main/java/com/backbase/stream/config/BackbaseStreamConfigurationProperties.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/mappers/PaymentOrderTypeMapper.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/model/response/UpdatePaymentOrderIngestDbsResponse.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderTaskExecutor.java

The previous endpoint (https://developer.backbase.com/apis/specs/payment/payment-order-service-api/2.11.0/operations/PaymentOrders/putUpdateStatus/), 
did not allow for nextExecutionDate and requestedExecutionDate to be updated.
I replaced the update with another endpoint to solve this (https://developer.backbase.com/apis/specs/payment/payment-order-service-api/2.11.0/operations/PaymentOrders/putUpdateStatus/)

adding requestedExecutionDate and nextExecutionDate update

---

CHANGELOG.md
stream-product/product-core/src/main/java/com/backbase/stream/product/mapping/ProductMapper.java
stream-product/product-core/src/test/java/com/backbase/stream/product/mapping/ProductMapperTest.java

The field AccountArrangementItem::currentInvestmentValue is not mapped to InvestmentAccount::currentInvestment because of the name difference. This PR fixes given mapping issue.

Fix 'current investment' mapping for the InvestmentAccount.

---

CHANGELOG.md
api/stream-portfolio/schemas/v1/portfolio.yaml

starting from 2023.03 it's mandatory for portfolio

Updated stream `portfolio.yaml` schema to include `arrangementId`.

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java
stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/AccessGroupServiceTest.java

**Description:**
In the recent April release, there is a new validation check in DBS access control for the putAssignUserPermissions operation where upon having duplicated dataGroupIdentifiers in the request the DBS reject it with the below error. Stream was having this bug before but without any side-effect and it got exposed while using the latest DBS version.
```
Data groups cannot be duplicated in scope of a single function group during assigning permissions
```

Fix Duplicate dataGroupIdentifiers for functionGroupDataGroups in putAssignUserPermissions API Call

---

CHANGELOG.md
stream-compositions/api/integrations-api/product-integration-api/src/main/resources/service-api-v2.yaml
stream-compositions/api/integrations-api/transaction-integration-api/src/main/resources/service-api-v2.yaml
stream-compositions/api/service-api/product-composition-api/src/main/resources/service-api-v2.yaml
stream-compositions/api/service-api/transaction-composition-api/src/main/resources/service-api-v2.yaml
stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/mapper/ProductRestMapper.java
stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/model/ProductIngestPullRequest.java
stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/service/impl/ProductIntegrationServiceImpl.java
stream-compositions/services/transaction-composition-service/src/main/java/com/backbase/stream/compositions/transaction/core/model/TransactionIngestResponse.java
stream-compositions/services/transaction-composition-service/src/main/java/com/backbase/stream/compositions/transaction/core/service/impl/TransactionIngestionServiceImpl.java
stream-compositions/services/transaction-composition-service/src/main/java/com/backbase/stream/compositions/transaction/core/service/impl/TransactionIntegrationServiceImpl.java
stream-compositions/services/transaction-composition-service/src/main/java/com/backbase/stream/compositions/transaction/http/TransactionController.java

Cherry picking of changes implemented in PR https://github.com/Backbase/stream-services/pull/311 and released in version `3.33.2`.
The idea here is to be able to propagate additions returned by the integration layer response to the composition layer response.
```
ProductIngestionResponse.additions -> ProductIngestionResponse.additions
PullTransactionsResponse.additions -> TransactionIngestResponse.additions
```

Addition propagation

---

CHANGELOG.md
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderUnitOfWorkExecutor.java

I removed the parameter used for the Payment Orders filter request. This was causing issues in the newer versions of DBS.
- [x ] I made sure to update [CHANGELOG.md](CHANGELOG.md).
- [ N/A] I made sure to update [Stream Wiki](https://github.com/Backbase/stream-services/wiki)(only valid in case of new stream module or architecture changes).

updating payment filter request

---

CHANGELOG.md
pom.xml

Fix: update dbs clients to 2023.06.2
- [ x ] I made sure, I read [CONTRIBUTING.md](CONTRIBUTING.md) to put right branch prefix as per my need.
- [ x ] I made sure to update [CHANGELOG.md](CHANGELOG.md).
- [ x ] I made sure to update [Stream Wiki](https://github.com/Backbase/stream-services/wiki)(only valid in case of new stream module or architecture changes).
- [ x ] My changes are adequately tested.
- [ x ] I made sure all the SonarCloud Quality Gate are passed.

Fix: update dbs clients to 2023.06.2

---

CHANGELOG.md
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderUnitOfWorkExecutor.java

The 2023.02 version of Payments will only bring back 10 payments by default, unless specified otherwise. This will bring back all payments associated with the user. 
A PR to merge this to the newer streams will also be opened.

updating pmts filter to include large range

---

CHANGELOG.md
stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java
stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/configuration/LegalEntitySagaConfiguration.java

- add check for LE not having users before processing. (should fix error when LE is empty)
- add AudiencesSegmentationConfiguration to LegalEntitySagaConfiguration

Check if LE users is null or empty for audiences segmentation

---

CHANGELOG.md
stream-limits/limits-core/src/main/java/com/backbase/stream/configuration/LimitsServiceConfiguration.java
stream-limits/limits-core/src/main/java/com/backbase/stream/configuration/LimitsWorkerConfigurationProperties.java
stream-limits/limits-core/src/main/java/com/backbase/stream/limit/LimitsSaga.java
stream-limits/limits-core/src/test/java/com/backbase/stream/limit/LimitsSagaTest.java

- Add feature flag for limits ingestion default is true, `backbase.stream.limits.worker.enabled`

Add feature flag for limits ingestion default is true

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java
stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/AccessGroupServiceTest.java
stream-compositions/services/legal-entity-composition-service/src/main/resources/application-local.yml
stream-compositions/services/legal-entity-composition-service/src/main/resources/application.yml
stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java
stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/configuration/LegalEntitySagaConfigurationProperties.java
stream-legal-entity/legal-entity-core/src/test/java/com/backbase/stream/LegalEntitySagaTest.java
stream-legal-entity/legal-entity-http/src/test/java/com/backbase/stream/it/LegalEntitySagaIT.java

At the moment once a secondary service agreement is created it can not be updated via streams. This PR allows updates to secondary service agreement. The change is specifically needed to allow Service Agreement `additions` modifications along with the rest of the SSA attributes. 
The feature is configurable and can be enabled or disables by the following flag `backbase.stream.legalentity.sink.serviceAgreementUpdateEnabled`
- [x ] I made sure, I read [CONTRIBUTING.md](CONTRIBUTING.md) to put right branch prefix as per my need.
- [x ] I made sure all the SonarCloud Quality Gate are passed.

added service agreement update to secondary service agreements

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/mapper/UserMapper.java
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/UserService.java
stream-legal-entity/legal-entity-bootstrap-task/src/test/java/com/backbase/stream/SetupLegalEntityHierarchyTaskApplicationIT.java
stream-legal-entity/legal-entity-bootstrap-task/src/test/resources/mappings/get-identity.json
stream-legal-entity/legal-entity-bootstrap-task/src/test/resources/mappings/put-identity.json
stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java
stream-legal-entity/legal-entity-core/src/test/java/com/backbase/stream/LegalEntitySagaTest.java
stream-legal-entity/legal-entity-http/src/test/java/com/backbase/stream/it/LegalEntitySagaIT.java

Add: update identity user attributes in case it was already created.

Add: update identity user attributes in case it was already created

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/configuration/AccessControlConfiguration.java
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/UserService.java
stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/UserServiceTest.java
stream-dbs-clients/src/main/java/com/backbase/stream/clients/config/UserManagerClientConfig.java
stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java
stream-legal-entity/legal-entity-core/src/test/java/com/backbase/stream/LegalEntitySagaTest.java

Implemented the retrieval of user profile data from the user manager to populate the user manager cache with profile information.

add populating user manager cache with ingested user profile data

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java
stream-sdk/stream-parent/stream-worker/src/main/java/com/backbase/stream/worker/model/StreamTask.java

Fix formatting of StreamTask error messages

Fix formatting of StreamTask error messages

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java
stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/AccessGroupServiceTest.java
stream-compositions/services/legal-entity-composition-service/src/main/resources/application-local.yml
stream-compositions/services/legal-entity-composition-service/src/main/resources/application.yml
stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java
stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/configuration/LegalEntitySagaConfigurationProperties.java
stream-legal-entity/legal-entity-core/src/test/java/com/backbase/stream/LegalEntitySagaTest.java
stream-legal-entity/legal-entity-http/src/test/java/com/backbase/stream/it/LegalEntitySagaIT.java

At the moment once a secondary service agreement is created it can not be updated via streams. This PR allows updates to secondary service agreement. The change is specifically needed to allow Service Agreement additions modifications along with the rest of the SSA attributes.
The feature is configurable and can be enabled or disables by the following flag `backbase.stream.legalentity.sink.serviceAgreementUpdateEnabled`
- [] I made sure to update [Stream Wiki](https://github.com/Backbase/stream-services/wiki)(only valid in case of new stream module or architecture changes). ~ N/A

Secondary Service Agreement update functionality

---

CHANGELOG.md
pom.xml
stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/service/impl/ProductPostIngestionServiceImpl.java
stream-compositions/services/transaction-composition-service/src/main/java/com/backbase/stream/compositions/transaction/core/service/impl/TransactionPostIngestionServiceImpl.java
stream-compositions/services/transaction-composition-service/src/test/java/com/backbase/stream/compositions/transaction/core/service/impl/TransactionIngestionServiceImplTest.java

When transaction ingestion fails return a failure response so the transaction composition consumer can handle it accordingly.
- [x ] I made sure all the SonarCloud Quality Gate are passed.

Return error when transaction ingestion fails

---

CHANGELOG.md
stream-compositions/services/transaction-composition-service/src/main/java/com/backbase/stream/compositions/transaction/core/service/impl/TransactionIngestionServiceImpl.java
stream-compositions/services/transaction-composition-service/src/test/java/com/backbase/stream/compositions/transaction/core/service/impl/TransactionIngestionServiceImplTest.java

Check and create cursor if it does not exist even if the `dateRangeStart` is present in `TransactionIngestPullRequest `. If End Date is passed set the `lastTxnDate` to `TransactionIngestPullRequest.getDateRangeEnd()`
- [ X] I made sure, I read [CONTRIBUTING.md](CONTRIBUTING.md) to put right branch prefix as per my need.
- [ X] I made sure to update [CHANGELOG.md](CHANGELOG.md).
- [ X ] My changes are adequately tested.
- [ X] I made sure all the SonarCloud Quality Gate are passed.

Always check cursor and create if it does not exist

---

CHANGELOG.md
pom.xml
stream-compositions/cursors/transaction-cursor/pom.xml
stream-compositions/cursors/transaction-cursor/src/main/resources/application-local.yml

With the change to use `spring-cloud-starter-kubernetes-fabric8`, we needed to also add the `service-sdk-starter-mapping` dependency to transaction-cursor. 
- [ N/A] I made sure to update [Stream Wiki](https://github.com/Backbase/stream-services/wiki)(only valid in case of new stream module or architecture changes).
- [x ] My changes are adequately tested.
- [x ] I made sure all the SonarCloud Quality Gate are passed.

transaction-cursor: fix dependency issue - fix local config

---

CHANGELOG.md
api/stream-legal-entity/openapi.yaml

CORS-1893 -  add cards reference to JobProfileUser to change the way cards are ingested in optima way

CORS-1893 - add cards reference to JobProfileUser

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/configuration/AccessControlConfiguration.java
stream-access-control/access-control-core/src/main/java/com/backbase/stream/configuration/UserManagementProperties.java
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/UserService.java
stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/UserServiceTest.java
stream-compositions/services/legal-entity-composition-service/src/main/resources/application-local.yml
stream-compositions/services/legal-entity-composition-service/src/main/resources/application.yml

This PR contains add a flag to skip updates to User in Identity. After the recent Identity and Core Service Upgrade (`2023.09-LTS`) simultaneously updates to the Identity User often results in `HTTP 409 Conflict` this happens in the scenarios where there are more than 1 service agreements for a single user (i.e. one for Retail and other for Business). To make the change seamless for existing consumers the default value is set to true. 
Reference ISD ticket: https://backbase.atlassian.net/servicedesk/customer/portal/27/ISD-318
- [ N/A] I made sure to update [Stream Wiki](https://github.com/Backbase/stream-services/wiki)(only …

Added a flag to skip identity updates

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/configuration/AccessControlConfiguration.java
stream-access-control/access-control-core/src/main/java/com/backbase/stream/configuration/UserManagementProperties.java
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/UserService.java
stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/UserServiceTest.java
stream-compositions/services/legal-entity-composition-service/src/main/resources/application-local.yml
stream-compositions/services/legal-entity-composition-service/src/main/resources/application.yml

This PR contains changes to add a flag to skip updates to User in Identity. After the recent Identity and Core Service Upgrade (2023.09-LTS) simultaneously updates to the Identity User often results in HTTP 409 Conflict this happens in the scenarios where there are more than 1 service agreements for a single user (i.e. one for Retail and other for Business). To make the change seamless for existing consumers the default value is set to true.
Reference ISD ticket: https://backbase.atlassian.net/servicedesk/customer/portal/27/ISD-318
- [ N/A] I made sure to update [Stream …

toggle identity user updates

---

stream-compositions/services/payment-order-composition-service/src/main/java/com/backbase/stream/compositions/paymentorders/core/service/impl/PaymentOrderPostIngestionServiceImpl.java
stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/mapper/ProductRestMapper.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderUnitOfWorkExecutor.java
stream-payment-order/payment-order-core/src/test/java/com/backbase/stream/common/PaymentOrderBaseTest.java
stream-payment-order/payment-order-core/src/test/java/com/backbase/stream/task/PaymentOrderUnitOfWorkExecutorTest.java

1. Fixed issue with payment order ingestion error, where it was not paging if the user had lots of objects in the same request.
2. Added changes to show error in case of error while payment order ingestion.
3. Fixed issue in down stream request where chaining was not being propogated in product-composition-service.

Fixed issue with payment order ingestion, where it was not paging if the user had lots of objects in the same request.

---

stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java
stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/AccessGroupServiceTest.java

When using REPLACE as ingestion mode for data groups they are removed if not specified as a product. In some cases, like engagement permissions, we need to look at provided data groups and replace those in the system.

Adding logic to handle repositories type group when updating existing data grouop

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java
stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/AccessGroupServiceUpdateFunctionGroupsTest.java

Fix the issue with creating job roles in CSA as template by default

MAINT-29996 - fix reference job roles creation only for master

---

CHANGELOG.md
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderUnitOfWorkExecutor.java
stream-payment-order/payment-order-core/src/test/java/com/backbase/stream/task/PaymentOrderUnitOfWorkExecutorTest.java

Fixed issue with payment order ingestion error, where it was not paging if the user had lots of objects in the same request.
Fixed issue with payment order ingestion error, where it was not paging if the user had lots of objects in the same request.
- [ N/A] I made sure to update [Stream Wiki](https://github.com/Backbase/stream-services/wiki)(only valid in case of new stream module or architecture changes).
- [ x] I made sure all the SonarCloud Quality Gate are passed.

Fixed issue with payment order ingestion

---

CHANGELOG.md
stream-compositions/pom.xml
stream-sdk/pom.xml
stream-sdk/stream-starter-parents/stream-http-starter-parent/pom.xml
stream-sdk/stream-starter-parents/stream-task-starter-parent/pom.xml
stream-sdk/stream-starter/pom.xml

new module stream-starter was missed in the stream-sdk (parent) module. it was the reason that it was not released.

NOJIRA: fixed missing stream-starter module in stream-sdk

---

CHANGELOG.md
stream-contacts/contacts-core/src/main/java/com/backbase/stream/configuration/ContactsServiceConfiguration.java
stream-contacts/contacts-core/src/main/java/com/backbase/stream/contact/ContactsSaga.java
stream-contacts/contacts-core/src/test/java/com/backbase/stream/contact/ContactsSagaTest.java

Make use of continueOnError flag for Contacts ingestion. Currently subsequent runs of bootstrap with contacts fail on contacts re-ingestion and require cleanup of contact DB which is very annoying for development

Maint 31100 contacts conditional

---

CHANGELOG.md
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/config/PaymentOrderTypeConfiguration.java
stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderUnitOfWorkExecutor.java
stream-payment-order/payment-order-core/src/test/java/com/backbase/stream/task/PaymentOrderUnitOfWorkExecutorTest.java

Added configuration to filter payments by ExecutionDateFrom based in offset period days

Added ExecutionDateFrom filter in payment order based on configuration 

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/UserService.java
stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/UserServiceTest.java
stream-legal-entity/legal-entity-http/src/test/java/com/backbase/stream/it/LegalEntitySagaIT.java
stream-product/product-core/src/main/java/com/backbase/stream/product/service/ArrangementService.java
stream-product/product-core/src/test/java/com/backbase/stream/product/service/ArrangementServiceTest.java
stream-product/product-ingestion-saga/pom.xml
stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/ProductIngestionSaga.java
stream-product/product-ingestion-saga/src/test/java/com/backbase/stream/product/BatchProductIngestionSagaTest.java
stream-product/product-ingestion-saga/src/test/java/com/backbase/stream/product/MockUtil.java
stream-product/product-ingestion-saga/src/test/java/com/backbase/stream/product/ProductIngestionSagaTest.java

Perfomance fix during upsertUser processing. If the internalId is available, call getUserById (8 ms response time) instead of getUserByExternalId (~ 50 ms response time).
- [NA] I made sure, I read [CONTRIBUTING.md](CONTRIBUTING.md) to put right branch prefix as per my need.
- [NA] I made sure to update [Stream Wiki](https://github.com/Backbase/stream-services/wiki)(only valid in case of new stream module or architecture changes).

Performance Improvement to use getUserById when internalId is available

---

CHANGELOG.md
stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/service/impl/ArrangementIngestionServiceImpl.java
stream-compositions/services/product-composition-service/src/test/java/com/backbase/stream/compositions/product/http/ProductControllerIT.java
stream-product/product-core/src/main/java/com/backbase/stream/product/service/ArrangementService.java
stream-product/product-core/src/test/java/com/backbase/stream/product/service/ArrangementServiceTest.java
stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/ProductIngestionSaga.java

Fix - Modified invocation of the putArrangementById API to provide the internal ID of the arrangement instead of the external ID

Fix - Modified invocation of the putArrangementById API to provide the internal ID of the arrangement instead of the external ID

---

CHANGELOG.md
stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/ServiceAgreementSagaV2.java

MAINT-32325 - fixed setting creatorLE in reactive chain

MAINT-32325 - fix the logic of setting internal id for creatorLE

---

CHANGELOG.md
stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java
stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/AccessGroupServiceUpdateFunctionGroupsTest.java

Fix the logic to respect the provided type of a job role while ingestion

MAINT-33753 - backport the fix for proper job roles creation

---

pom.xml

Triggering build because previous commit contains `[skip bump] version bump` commit message.

Dummy commit to trigger build

---

CHANGELOG.md
README.md
api/stream-legal-entity/openapi.yaml
stream-compositions/events/events/product/base-product-group.json

Adds new data group types that are supported by Access Control as of `2025.04`.
- [N/A] I made sure to update [Stream Wiki](https://github.com/Backbase/stream-services/wiki)(only valid in case of new stream module or architecture changes).
- [N/A] My changes are adequately tested.

Add new Data Group types
