api/stream-legal-entity/openapi.yaml, api/stream-legal-entity/v1.0.0/openapi.yaml, api/stream-legal-entity/v1.1.0/openapi.yaml
=> Added BBAN to TermDeposit

.github/workflows/build.yml, api/stream-legal-entity/openapi.yaml, stream-access-control/access-control-core/src/main/java/com/backbase/stream/mapper/UserProfileMapper.java, stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/UserProfileService.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/configuration/LegalEntitySagaConfiguration.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/configuration/LegalEntitySagaConfigurationProperties.java
Ingest user profile (for dbs user-profile-manager) as part of legal entity ingestion. Disabled by default as many envs don't have user-profile-manager capability in place
=> Add user profile to saga

stream-dbs-clients/pom.xml
Added the 'User' manager model to the 'additions' transformer
=> Update stream-dbs-clients pom.xml

CHANGELOG.md, api/stream-legal-entity/openapi.yaml, stream-access-control/access-control-core/pom.xml, stream-access-control/access-control-core/src/main/java/com/backbase/stream/mapper/AccessGroupMapper.java, stream-access-control/access-control-core/src/main/java/com/backbase/stream/mapper/ParticipantMapper.java, stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java, stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/UserService.java, stream-access-control/access-control-core/src/test/java/com/backbase/stream/mapper/AccessGroupMapperTest.java, stream-access-control/access-control-core/src/test/java/com/backbase/stream/mapper/ParticipantMapperTest.java, stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/AccessGroupServiceTest.java, stream-access-control/access-control-core/src/test/java/com/backbase/stream/test/LambdaAssertions.java, stream-access-control/access-control-core/src/test/java/com/backbase/stream/test/WebClientTestUtils.java, stream-legal-entity/legal-entity-core/pom.xml, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/UpdatedServiceAgreementSaga.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/UpdatedServiceAgreementTask.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/UpdatedServiceAgreementUnitOfWorkExecutor.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/configuration/UpdatedServiceAgreementSagaConfiguration.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/configuration/UpdatedServiceAgreementSagaConfigurationProperties.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/legalentity/repository/UpdatedServiceAgreementUnitOfWorkRepository.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/mapper/ProductGroupMapper.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/mapper/UnitOfWorkMapper.java, stream-legal-entity/legal-entity-core/src/test/test/com/backbase/stream/LegalEntitySagaTest.java, stream-legal-entity/legal-entity-core/src/test/test/com/backbase/stream/UpdatedServiceAgreementSagaTest.java, stream-legal-entity/legal-entity-http/pom.xml, stream-legal-entity/legal-entity-http/src/main/java/com/backbase/stream/controller/LegalEntityAsyncController.java, stream-legal-entity/legal-entity-http/src/main/java/com/backbase/stream/controller/ServiceAgreementController.java, stream-legal-entity/legal-entity-http/src/test/java/com/backbase/stream/LegalEntityHttpApplicationTest.java
- Custom Service Agreement in Legal Entity Upsert
- Update Service Agreement endpoint
=> Third Party Access: Custom Service Agreement in Legal Entity Upsert

CHANGELOG.md, api/stream-legal-entity/openapi.yaml, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java, stream-product/product-core/src/main/java/com/backbase/stream/product/utils/StreamUtils.java, stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/BatchProductIngestionSaga.java, stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/ProductIngestionSaga.java
- Fix for null point exception when no users are informed during the legal entity bootstrap.
- Enhancements in utility for aggregating all products of a product group.
- Enhanced the documentation for Service Agreements endpoints.
- Updated changelog with previous documented versions
=> Fix for null point exception when no users are informed during the legal entity bootstrap

stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java
Fixing the getuser call to be called using the internal id  @jlimamob
=> fix for issue #46

stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java, stream-product/product-core/src/main/java/com/backbase/stream/product/utils/StreamUtils.java, stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/BatchProductIngestionSaga.java, stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/ProductIngestionSaga.java
=> Enabling Stream to create Product group without Product and with Custom data group id

CHANGELOG.md, api/stream-legal-entity/openapi.yaml, pom.xml, stream-access-control/access-control-core/src/main/java/com/backbase/stream/configuration/AccessControlConfiguration.java, stream-access-control/access-control-core/src/main/java/com/backbase/stream/mapper/UserMapper.java, stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/UserService.java, stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/UserServiceTest.java, stream-configuration/src/main/java/com.backbase.stream.config/BackbaseStreamConfigurationProperties.java, stream-dbs-clients/pom.xml, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java, stream-legal-entity/legal-entity-http/src/test/java/com/backbase/stream/LegalEntityHttpApplicationTest.java
Legal Entity Ingestion: disable/lock identity user at creation
=> Identity user lock on creation

CHANGELOG.md
Changelog for 2.33.0 was added to 2.32.0 instead
=> Add missing changelog for 2.33.0

stream-sdk/stream-parent/pom.xml, stream-sdk/stream-parent/stream-dbs-web-client/pom.xml, stream-sdk/stream-parent/stream-dbs-web-client/src/main/java/com/backbase/stream/webclient/DbsWebClientConfiguration.java, stream-sdk/stream-parent/stream-dbs-web-client/src/main/java/com/backbase/stream/webclient/configuration/DbsWebClientConfigurationProperties.java, stream-sdk/stream-parent/stream-dbs-web-client/src/test/java/com/backbase/stream/webclient/DbsWebClientConfigurationTest.java, stream-sdk/stream-parent/stream-test-support/src/main/java/com/backbase/stream/AbstractServiceIntegrationTests.java, stream-sdk/stream-starter-parents/stream-sdk-starter-core/pom.xml
Added DbsWebClientConfigurationProperties for configurating additonal headers such as X-TID
Upgraded Jacoco to 0.8.7 to  support compilation on Java 15
=> Added m10y support in DBS Web Client

CHANGELOG.md, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java, stream-legal-entity/legal-entity-core/src/test/java/com/backbase/stream/LegalEntitySagaTest.java
Thanks to Joao catching potential issue
=> Return stream at link le to realm task if filters not matched

CHANGELOG.md, stream-access-control/access-control-core/src/main/java/com/backbase/stream/mapper/AccessGroupMapper.java, stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java, stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/AccessGroupServiceUpdateFunctionGroupsTest.java
=> Upserting referenceJobRoles does not work #14;

CHANGELOG.md, Makefile, pom.xml, stream-access-control/access-control-core/pom.xml, stream-approvals/approvals-core/pom.xml, stream-configuration/pom.xml, stream-cursor/cursor-http/pom.xml, stream-dbs-clients/pom.xml, stream-legal-entity/legal-entity-bootstrap-task/pom.xml, stream-legal-entity/legal-entity-core/pom.xml, stream-legal-entity/legal-entity-http/pom.xml, stream-models/approval-model/pom.xml, stream-models/legal-entity-model/pom.xml, stream-models/pom.xml, stream-models/product-catalog-model/pom.xml, stream-product-catalog/product-catalog-core/pom.xml, stream-product-catalog/product-catalog-http/pom.xml, stream-sdk/stream-parent/pom.xml, stream-sdk/stream-starter-parents/stream-aio-starter-parent/pom.xml, stream-sdk/stream-starter-parents/stream-http-starter-parent/pom.xml, stream-sdk/stream-starter-parents/stream-processor-starter-parent/pom.xml, stream-sdk/stream-starter-parents/stream-sdk-starter-core/pom.xml, stream-sdk/stream-starter-parents/stream-sink-starter-parent/pom.xml, stream-sdk/stream-starter-parents/stream-source-starter-parent/pom.xml, stream-sdk/stream-starter-parents/stream-task-starter-parent/pom.xml, stream-transactions/transactions-core/pom.xml, stream-transactions/transactions-http/pom.xml
Cleaned up versions for boat-maven-plugin
Added spring-boot-configuration-processors to modules that have configuration classes
Moved Product Catalog Model to own package to prevent deep transitive dependencies
Removed scdf-maven-plugin. This is now a configuration per project if required
=> Housekeeping

CHANGELOG.md, pom.xml, readme.md, stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/UserProfileService.java, stream-dbs-clients/pom.xml, stream-legal-entity/legal-entity-core/pom.xml, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/configuration/LegalEntitySagaConfiguration.java, stream-product/product-core/src/main/java/com/backbase/stream/product/service/ArrangementService.java, stream-sdk/pom.xml, stream-sdk/stream-parent/pom.xml, stream-sdk/stream-starter-parents/stream-processor-starter-parent/pom.xml, stream-sdk/stream-starter-parents/stream-sdk-starter-core/pom.xml, stream-transactions/transactions-core/src/main/java/com/backbase/stream/TransactionService.java, stream-transactions/transactions-core/src/main/java/com/backbase/stream/transaction/TransactionTaskExecutor.java
Replacing the two product boms (dbs banking services bom and identity bom) with the new Backbase bom.
Updating to 2021.07 (DBS 2.21.0.1 & Identity 1.9.0.1)
Resolving compilation issues caused by newly added api parameters.
Not sure how to test this.
Not sure this should be a minor version of stream.
=> Introduce backbase-bom; update to 2021.07

api/stream-legal-entity/openapi.yaml, stream-access-control/access-control-core/src/main/java/com/backbase/stream/mapper/LegalEntityMapper.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java, stream-legal-entity/legal-entity-core/src/test/java/com/backbase/stream/LegalEntitySagaTest.java
Added support for 
1. LegalEntity
i. activateSingleServiceAgreement
ii. additions
1. ServiceAgreement 
i. creatorLegalEntity
=> Added support for activateSingleServiceAgreement and additions in LegalEntity and creatorLegalEntity in ServiceAgreement

stream-sdk/stream-parent/stream-dbs-web-client/src/main/java/com/backbase/stream/webclient/DbsWebClientConfiguration.java
In a project that's using the stream library to ingest users in the BB database, we've found out that there's a leak happening. 
Here's an example of the error log:
```
2022-02-11 14:48:44.862 ERROR [cmf-bb-ingestion-service,,] 1 --- [or-http-epoll-4] io.netty.util.ResourceLeakDetector       : LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
+[ Recent access records: 
+[ #1:
+[ 	Hint: [id:8420768a-4, L:/10.42.0.149:50942 - R:access-control.svc.cluster.local/10.43.201.195:8080] Buffered ByteBufHolder in the inbound buffer queue
+[ 	io.netty.handler.codec.http.DefaultHttpContent.touch(DefaultHttpContent.java:86)
+[ 	io.netty.handler.codec.http.DefaultLastHttpContent.touch(DefaultLastHttpConten …
```
=> Fix a memory leak issue in the CSRF filter of the web client

CHANGELOG.md, stream-sdk/stream-parent/pom.xml, stream-sdk/stream-starter-parents/stream-sdk-starter-core/pom.xml
Fix for https://tanzu.vmware.com/security/cve-2022-22965 and https://tanzu.vmware.com/security/cve-2022-22963
=> Update Spring Boot to 2.5.12 and Spring Cloud Function to 3.1.7

CHANGELOG.md, stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java, stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/AccessGroupServiceUpdateFunctionGroupsTest.java
=> Handle update job role HTTP 207 multi-status response 

README.md
Adding clarity of text as an Accelerator - not to be confused with OOTB components.
=> Adding detail that this project is an accelerator

stream-contacts/contacts-core/pom.xml, stream-contacts/pom.xml
Corrected version of Contacts and Contacts-Core modules
=> - Corrected version

.github/workflows/build.yml, CHANGELOG.md, stream-access-control/access-control-core/pom.xml, stream-approvals/approvals-bootstrap-task/src/main/resources/application.yml, stream-approvals/approvals-core/pom.xml, stream-legal-entity/legal-entity-bootstrap-task/src/main/resources/application.yml, stream-legal-entity/legal-entity-bootstrap-task/src/test/java/com/backbase/stream/SetupLegalEntityHierarchyTaskApplicationIT.java, stream-legal-entity/legal-entity-core/pom.xml, stream-portfolio/portfolio-bootstrap-task/pom.xml, stream-portfolio/portfolio-bootstrap-task/src/main/resources/application.yml, stream-portfolio/portfolio-core/pom.xml, stream-product-catalog/product-catalog-task/src/main/resources/application.yml, stream-sdk/stream-parent/stream-test-support/pom.xml, stream-sdk/stream-starter-parents/stream-http-starter-parent/pom.xml, stream-sdk/stream-starter-parents/stream-task-starter-parent/pom.xml
=> Deploying Stream Services as docker images

CHANGELOG.md, api/stream-legal-entity/openapi.yaml
Added this missing entity in the BaseProduct
https://developer.backbase.com/api/specs/arrangement-manager/arrangement-service-api/2.6.0/models/InterestDetails
=> Added InterestDetails to BaseProduct

CHANGELOG.md, stream-compositions/api/integrations-api/payment-order-integration-api/src/main/resources/service-api-v2.yaml, stream-compositions/api/service-api/payment-order-composition-api/src/main/resources/service-api-v2.yaml, stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/service/impl/ProductIngestionServiceImpl.java, stream-sdk/stream-parent/stream-worker/src/main/java/com/backbase/stream/worker/UnitOfWorkExecutor.java, stream-transactions/transactions-core/src/main/java/com/backbase/stream/transaction/TransactionTaskExecutor.java
No review is required at this stage. Will merge this with the memory leak changes first.
=> adding mapping changes

CHANGELOG.md, stream-compositions/services/product-composition-service/README.md, stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/config/ProductConfigurationProperties.java, stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/service/impl/ProductIngestionServiceImpl.java, stream-compositions/services/product-composition-service/src/main/resources/application.yml
Added ingestion mode config in product composition. Example:
```
ingestion-mode:
function-groups: UPSERT
data-groups: UPSERT
arrangements: UPSERT
```
=> Added ingestion mode config in product composition

CHANGELOG.md, stream-approvals/approvals-bootstrap-task/src/main/resources/application-local.yml, stream-compositions/cursors/transaction-cursor/pom.xml, stream-compositions/cursors/transaction-cursor/src/main/resources/application-local.yml, stream-compositions/services/product-composition-service/src/main/resources/application-local.yml
aded mysql dependency and other minor tweaks in local profiles
=> Fixed local setup issues

CHANGELOG.md, stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/UserService.java
Port the user addition hot fix from 3.15.2 to master
=> Port the user addition hot fix from 3.15.2 to master

CHANGELOG.md, stream-product/product-core/src/main/java/com/backbase/stream/product/mapping/ProductMapper.java, stream-product/product-core/src/test/java/com/backbase/stream/product/mapping/ProductMapperTest.java
The second PR, the first one did not completely solved the issue. This one fixes second part of the mapping.
Also fixed version numbering as previous PR created major version bump after a squash PR merge.
=> Fix current investment mapping.

CHANGELOG.md, api/stream-legal-entity/openapi.yaml, api/stream-product-catalog/openapi.yaml
Updated stream product-catalog/openapi.yaml schema to include accountHolderName
=> Updated stream `product-catalog/openapi.yaml` schema to include `accountHolderName`

stream-compositions/api/service-api/product-composition-api/src/main/resources/service-api-v2.yaml, stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/mapper/ProductRestMapper.java, stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/model/ProductIngestPullRequest.java, stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/model/ProductIngestResponse.java, stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/service/impl/ProductIngestionServiceImpl.java, stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/service/impl/ProductIntegrationServiceImpl.java, stream-compositions/services/product-composition-service/src/main/java/com/backbase/stream/compositions/product/core/service/impl/ProductPostIngestionServiceImpl.java
Enabling chaining on product pull request .This is the task associated with it  https://backbase.atlassian.net/jira/software/c/projects/STRO/boards/1797?modal=detail&selectedIssue=STRO-56
=> Adding Chaining enabled or disabled on the product pull request

CHANGELOG.md, stream-dbs-clients/src/main/java/com/backbase/stream/clients/config/AccessControlClientConfig.java
Add auto-configuration for user context service API in stream-dbs-clients module
=> Add auto-configuration for user context service API in stream-dbs-clients module

CHANGELOG.md
hotfix/rebuild for stream-dbs-client module change
=> hotfix/rebuild for stream-dbs-client module change

CHANGELOG.md, api/stream-legal-entity/openapi.yaml, api/stream-product-catalog/openapi.yaml
Updated stream `InvestmentAccount` schema to include `accountHolderNames`,`accountHolderCountry`,`BIC`
=> Updated InvestmentAccount schema

CHANGELOG.md, README.md, pom.xml, stream-compositions/api/integrations-api/payment-order-integration-api/src/main/resources/service-api-v2.yaml, stream-compositions/api/integrations-api/transaction-integration-api/src/main/resources/service-api-v2.yaml, stream-compositions/api/service-api/payment-order-composition-api/src/main/resources/service-api-v2.yaml, stream-compositions/api/service-api/transaction-composition-api/src/main/resources/service-api-v2.yaml, stream-compositions/pom.xml, stream-dbs-clients/pom.xml, stream-payment-order/payment-order-core/src/main/java/com/backbase/stream/paymentorder/PaymentOrderUnitOfWorkExecutor.java, stream-sdk/stream-parent/pom.xml, stream-sdk/stream-starter-parents/stream-http-starter-parent/pom.xml, stream-sdk/stream-starter-parents/stream-task-starter-parent/pom.xml, stream-transactions/transactions-core/src/main/java/com/backbase/stream/TransactionServiceImpl.java, stream-transactions/transactions-core/src/main/java/com/backbase/stream/transaction/TransactionTaskExecutor.java
- Upgraded SSDK to 15.2.0
- Upgraded Banking Services to 2023.02-LTS
- Fix some breaking changes introduced by 2023.02-LTS
=> Upgrade to support 2023-02-LTS

CHANGELOG.md, api/stream-legal-entity/openapi.yaml, stream-compositions/events/product-events/src/main/resources/events/base-product-group.json
Allows for ingesting data groups with type `CUSTOM`
=> Added support for `CUSTOM` data group type

CHANGELOG.md, stream-compositions/services/legal-entity-composition-service/src/main/java/com/backbase/stream/compositions/legalentity/core/service/impl/LegalEntityIngestionServiceImpl.java
Carry additions from legal entity request downstream.
=> Add addition propagation support to the legal entity ingestion request

CHANGELOG.md, api/stream-legal-entity/openapi.yaml
Add Additions to the DebitCardItem Model in the OpenApi Schema
=> Add Additions to DebitCardItem OpenApi Schema Model

.github/pull_request_template.md, CHANGELOG.md
Recently I noticed, Stream contributors are not adding enough information for reviewers when raising pull request. By adding this pull request template, it's one of step towards reminding developers to put PR description and they have performed the  common checklist which will help in maintaining quality
=> Created pull_request_template.md for stream contributors

.github/pull_request_template.md, .github/workflows/pull-request-body-validation.yml, CHANGELOG.md
New workflow to validate Pull request description and task list
=> New workflow to validate Pull request description and task list

CHANGELOG.md, README.md, api/stream-legal-entity/openapi.yaml, api/stream-portfolio/schemas/v1/position.yaml, pom.xml, stream-compositions/api/integrations-api/payment-order-integration-api/src/main/resources/service-api-v2.yaml, stream-compositions/api/service-api/payment-order-composition-api/src/main/resources/service-api-v2.yaml, stream-compositions/pom.xml, stream-dbs-clients/pom.xml, stream-loans/loans-core/src/test/java/com/backbase/stream/loan/LoansSagaTest.java
Upgrading Stream from `2023.02-LTS` to `2023.06`
Updated Portfolio's position stream contract to include new fields
=> Upgrading Stream from `2023.02-LTS` to `2023.06`

CHANGELOG.md, api/stream-portfolio/schemas/v1/aggregate-portfolio.yaml, stream-portfolio/portfolio-core/src/main/java/com/backbase/stream/portfolio/mapper/PortfolioMapper.java
Update portfolio aggregation model with externalId
=> Update portfolio aggregation model with externalId

CHANGELOG.md, stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/UserService.java, stream-access-control/access-control-core/src/test/java/com/backbase/stream/service/UserServiceTest.java
For the IMPORT_FROM_IDENTIY strategy use the user manager's importIdentity API call
=> IMPORT_FROM_IDENTIY use user manager's importIdentity API call

README.md
A few sentences describing the overall goals of the pull request's commits.
=> testing build

CHANGELOG.md, api/stream-legal-entity/openapi.yaml, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java, stream-legal-entity/legal-entity-http/src/test/java/com/backbase/stream/it/LegalEntitySagaIT.java, stream-legal-entity/legal-entity-http/src/test/resources/application-it.yml
Enhance Legal Entity level Limit Object to set Limit based on Privilege, Business Function and Legal Entity
=> Enhance Legal Entity level Limit Object to set Limit based on Privilege, Business Function and Legal Entity

CHANGELOG.md, pom.xml, stream-product/product-core/src/main/java/com/backbase/stream/product/mapping/ProductMapper.java
Add AccountArrangementItemPut mapping in ProductMapper
=> Add AccountArrangementItemPut mapping in ProductMapper

CHANGELOG.md, api/stream-legal-entity/openapi.yaml, stream-compositions/services/legal-entity-composition-service/src/main/resources/application-local.yml
This PR is to add customer category to service agreement spec so it can be used by stream compositions.
- [ ~ N/A] I made sure to update [Stream Wiki](https://github.com/Backbase/stream-services/wiki)(only valid in case of new stream module or architecture changes).
- [ x] I made sure all the SonarCloud Quality Gate are passed.
=> service agreement category

CHANGELOG.md, pom.xml, stream-compositions/pom.xml, stream-sdk/stream-parent/stream-context-propagation/pom.xml, stream-sdk/stream-starter-parents/stream-http-starter-parent/pom.xml, stream-sdk/stream-starter-parents/stream-task-starter-parent/pom.xml
https://backbase.slack.com/archives/CG382F739/p1711465049567979
=> rolling out sdk fix

.vscode/settings.json, CHANGELOG.md, pom.xml, stream-limits/limits-core/src/main/java/com/backbase/stream/configuration/LimitsServiceConfiguration.java, stream-limits/limits-core/src/main/java/com/backbase/stream/configuration/LimitsWorkerConfigurationProperties.java, stream-limits/limits-core/src/main/java/com/backbase/stream/limit/LimitsSaga.java, stream-limits/limits-core/src/test/java/com/backbase/stream/limit/LimitsSagaTest.java
- Add feature flag for limits ingestion default is true, `backbase.stream.limits.worker.enabled`
=> hotfix Add feature flag for limits

.vscode/settings.json, CHANGELOG.md, stream-compositions/pom.xml
Upgrade stream composition to 2024.03.10-LTS
=> upgrade: Stream composition to 2024.03.10-LTS

.github/workflows/build.yml, CHANGELOG.md, api/stream-legal-entity/openapi.yaml, stream-compositions/events/events/product/base-product-group.json
add CUSTOMERS data group type to LE OpenAPI contract
=> add CUSTOMERS data group type

CHANGELOG.md
=> Trigger new build

stream-portfolio/portfolio-http/src/test/java/com/backbase/stream/portfolio/controller/it/PortfolioIT.java
print result when shouldIngestPortfolios fails
=> print unmatched requests when failing shouldIngestPortfolios test

CHANGELOG.md, stream-compositions/api/integrations-api/product-integration-api/pom.xml
To fix issues with generated models use BOAT when generating webclient for product integration api
- [ N/A] I made sure to update [Stream Wiki](https://github.com/Backbase/stream-services/wiki)(only valid in case of new stream module or architecture changes).
- [ x] I made sure all the SonarCloud Quality Gate are passed.
=> use BOAT when generating webclient for product integration api

stream-compositions/pom.xml
fix sdk plugin version override
=> fix sdk plugin version override

.github/workflows/build.yml, pom.xml, stream-compositions/pom.xml, stream-sdk/stream-parent/pom.xml, stream-sdk/stream-starter-parents/stream-http-starter-parent/pom.xml, stream-sdk/stream-starter-parents/stream-task-starter-parent/pom.xml
=> updating sdk version

stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java
=> Remove override sa name

CHANGELOG.md, api/stream-legal-entity/openapi.yaml, stream-product/product-core/src/main/java/com/backbase/stream/product/mapping/ProductMapper.java, stream-product/product-core/src/test/java/com/backbase/stream/product/mapping/ProductMapperTest.java
Adding additional mapping attributes to Credit card.
=> adding mapping fix

CHANGELOG.md, stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/BatchProductIngestionSaga.java, stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/ProductIngestionSaga.java
Performance improvement on function groups setup for ProductIngestionSaga
=> Performance improvement on function groups setup for ProductIngestionSaga

CHANGELOG.md, api/stream-legal-entity/openapi.yaml, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/mapper/ServiceAgreementV2ToV1Mapper.java
Add purpose field in service agreement specs .
=> DAS-1399 - add purpose field to service agreement

README.md
=> DAS-1399 - fix version mismatch

CHANGELOG.md, e2e-tests/stubs/mappings/mapping-service-api-v2-legal-entity.json, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java, stream-legal-entity/legal-entity-http/src/test/java/com/backbase/stream/it/LegalEntitySagaIT.java
[Enhancement] - Implemented User, Business function and PRV level limit ingetion functionality
=> [Enhancement] - Implemented User, Business function and PRV level limit ingetion functionality

CHANGELOG.md, stream-product/product-core/src/main/java/com/backbase/stream/product/service/ArrangementService.java, stream-product/product-core/src/test/java/com/backbase/stream/product/service/ArrangementServiceTest.java
Update ArrangementUpdateException Logger to handle PII data
- [NA] I made sure, I read [CONTRIBUTING.md](CONTRIBUTING.md) to put right branch prefix as per my need.
- [NA] I made sure to update [Stream Wiki](https://github.com/Backbase/stream-services/wiki)(only valid in case of new stream module or architecture changes).
=> Update ArrangementUpdateException Logger to handle PII data

CHANGELOG.md, stream-product-catalog/product-catalog-core/src/main/java/com/backbase/stream/productcatalog/ReactiveProductCatalogService.java, stream-product-catalog/product-catalog-task/src/test/resources/mappings/arrangement-manager-stubs.json
Bug fix in the `productTypeName` mapping when ingesting data into `arrangement-manager`.
- [N/A] I made sure to update [Stream Wiki](https://github.com/Backbase/stream-services/wiki)(only valid in case of new stream module or architecture changes).
=> MAINT-32872: Fix productTypeName mapping

CHANGELOG.md, pom.xml, stream-compositions/pom.xml, stream-sdk/stream-parent/pom.xml, stream-sdk/stream-starter/pom.xml
Upgrade of SDK to 18.1.0.
See [MAINT-32324](https://backbase.atlassian.net/browse/MAINT-32324) for info.
=> upgrade SDK to 18-1-0

stream-sdk/stream-starter/pom.xml
This is to handle Baas' Azure servicebus.
=> upgrading servicebus version

.github/workflows/build.yml, CHANGELOG.md, pom.xml
Upgrade to Backbase version `2024.03.68-LTS` and Service SDK to `16.1.11`
=> Hotfix 4.1.x - Upgrade to Backbase version `2024.03.68-LTS` and Service SDK to `16.1.11`

CHANGELOG.md, api/stream-legal-entity/openapi.yaml, stream-product/product-core/src/main/java/com/backbase/stream/product/service/ArrangementService.java, stream-product/product-core/src/test/java/com/backbase/stream/product/service/ArrangementServiceTest.java, stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/BatchProductIngestionSaga.java, stream-product/product-ingestion-saga/src/main/java/com/backbase/stream/product/ProductIngestionSaga.java, stream-product/product-ingestion-saga/src/test/java/com/backbase/stream/product/BatchProductIngestionSagaTest.java
Positive Pay capability needs to have appropriate subscriptions created for particular arrangements(accounts). The changes are part of effort to automate such an ingestions via bootstrap job.
=> PSTPAY-5201 Add subscriptions for arrangements

.github/workflows/build.yml
Update Cache version to cache@v3
=> Updated cached version to v3 (cache@v3)

CHANGELOG.md, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/LegalEntitySaga.java, stream-legal-entity/legal-entity-core/src/main/java/com/backbase/stream/configuration/LegalEntitySagaConfigurationProperties.java, stream-legal-entity/legal-entity-core/src/test/java/com/backbase/stream/LegalEntitySagaTest.java, stream-product/product-core/src/main/java/com/backbase/stream/product/task/BatchProductIngestionMode.java
Reverts Backbase/stream-services#513
=> Revert "Performance improvement on function groups setup for ProductIngestion…"

CHANGELOG.md, stream-access-control/access-control-core/src/main/java/com/backbase/stream/service/AccessGroupService.java
Improve logging of Job Role ingestion
=> NOJIRA - add job role name to error to make debugging easier

.github/workflows/build.yml, stream-product/product-core/src/main/java/com/backbase/stream/product/mapping/ProductMapper.java, stream-product/product-core/src/main/java/com/backbase/stream/product/mapping/ProductMapperConstants.java, stream-product/product-core/src/test/java/com/backbase/stream/product/mapping/ProductMapperTest.java
backported PR https://github.com/Backbase/stream-services/pull/485 to 5.16.x version
=> cherry pick from Hotfix/maint 32243 missed parent id mapping

CHANGELOG.md, stream-product/product-core/src/main/java/com/backbase/stream/product/mapping/ProductMapper.java, stream-product/product-core/src/main/java/com/backbase/stream/product/mapping/ProductMapperConstants.java, stream-product/product-core/src/test/java/com/backbase/stream/product/mapping/ProductMapperTest.java
This pull request improves the Product Mapper by aligning it with the latest core data structure, ensuring accurate and consistent data mapping. Additionally, it updates the associated test cases to reflect these changes and verify the mapper's functionality.
=> MAINT-35889: productMapper updated
